title: IOMED Data Space Platform
description: IOMED Data Space Platform documentation
theme: just-the-docs
color_scheme: custom

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
back_to_top: true
back_to_top_text: "Back to top"

url: https://docs.iomed.health
footer_content: 'Copyright &copy; 2017-2025 IOMED Medical Solutions SL.'
aux_links:
  Main Site: https://iomed.health

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


