collections:
  getting_started:
    output: true
  core_workflow:
    output: true
  package_reference:
    output: true
  educational_materials:
    output: true
  development_and_deployment:
    output: true
  data_and_methodology:
    output: true