title: IOMED Data Space Platform
description: IOMED Data Space Platform documentation
theme: just-the-docs
color_scheme: custom

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
back_to_top: true
back_to_top_text: "Back to top"

search:
  heading_level: 6
  previews: 4
  preview_words_before: 4
  focus_shortcut_key: 'k'

url: https://docs.iomed.health
footer_content: 'Copyright &copy; 2016-2026 IOMED Medical Solutions SL.'
enable_copy_code_button: true
aux_links:
  Main Site: https://iomed.health

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.0"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
